version: "3.9"

services:
  backend:
    build: ./backend/
    container_name: backend
    restart: always
    volumes: 
      - ./backend:/app
    ports: 
      - 3000:3000
    command: "npm run start:dev"
    depends_on:
      - database

  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    volumes: 
      - ./frontend:/app
    ports: 
      - 4200:4200
    environment:
      BASE_URL: "http://localhost:4200"
    command: "npm run start"
    depends_on:
      - backend

  database:
    image: "postgres"
    ports: 
      - 5432:5432
    env_file:
      - ./database/database.env
    volumes:
      - ./database/.data_tmp:/var/lib/postgresql/data
      - ./database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    
