version: "3"

services:
  backend:
    build: ./backend/
    container_name: backend
    restart: always
    volumes: 
      - ./backend:/app
    ports: 
      - 3000:3000
    command: "npm run start:dev"
    depends_on:
      - database

  database:
    image: "postgres"
    ports: 
      - 5432:5432
    env_file:
      - ./database/database.env
    volumes:
      - ./database/.tmp/db:/var/lib/postgresql/data
      - ./database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    
